services:
  mongo:
    image: mongo
    hostname: mongo-db
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - "27017:27017"
    networks:
      - mongo-network
  app_server:
    depends_on:
      - mongo
    build: python_app/
    image: python_app
    container_name: python_app
    restart: always
    volumes:
      - ./temp:/app/temp:rw
    networks:
      - mongo-network
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: example
      MONGODB_HOST: mongo-db
      MONGODB_DBNAME: medical_data
      MONGODB_COLLECTION_NAME: med_data_collection
      PYTHON_TEMP_DIR: /app/temp/
      PYTHON_BATCH_SIZE: 2000
networks:
   mongo-network:
      driver: bridge
      ipam:
         driver: default
